spring.application.name=GestionDesProduits
spring.datasource.url=jdbc:h2:mem:product-db
spring.datasource.username=anass
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
server.port=8085
spring.h2.console.enabled=true